service:
  name: stasisgg-backend
app: stasisgg-backend
org: rengkong

package:
  individually: false
  excludeDevDependencies: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  profile: stasisgg-backend
  region: ap-northeast-1

functions:
  get-last-10-matches:
    handler: src/get-last-10-matches/getLast10Matches.getLast10Matches
    events:
      - http:
          method: get
          path: get-last-10-matches
  get-one-match-card:
    handler: src/get-one-match-card/getOneMatchCard.getOneMatchCard
    events:
      - http:
          method: get
          path: get-one-match-card
  get-player-profile:
    handler: src/get-player-profile/getPlayerProfile.getPlayerProfile
    events:
      - http:
          method: get
          path: get-player-profile